//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hijo
    {
        public int idhijo { get; set; }
        public Nullable<int> id_tutoria { get; set; }
        public Nullable<int> id_padre { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual padre padre { get; set; }
        public virtual tutoria tutoria { get; set; }
    }
}
