//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensaje
    {
        public int idmensaje { get; set; }
        public string hora { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string contenido { get; set; }
        public Nullable<int> id_padre { get; set; }
        public Nullable<int> id_profe { get; set; }
        public string remitente { get; set; }
    
        public virtual padre padre { get; set; }
        public virtual profesor profesor { get; set; }
    }
}
