//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class metodopago
    {
        public metodopago()
        {
            this.profesors = new HashSet<profesor>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string numerotarjeta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string cvv { get; set; }
    
        public virtual ICollection<profesor> profesors { get; set; }
    }
}
