//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tutoria
    {
        public tutoria()
        {
            this.hijoes = new HashSet<hijo>();
            this.resumenclases = new HashSet<resumenclase>();
        }
    
        public int idtutoria { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string comentario { get; set; }
        public Nullable<int> calificacion { get; set; }
        public Nullable<int> id_padre { get; set; }
        public string estado { get; set; }
        public string curso { get; set; }
        public Nullable<int> id_horario { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public Nullable<int> numerohoras { get; set; }
    
        public virtual ICollection<hijo> hijoes { get; set; }
        public virtual padre padre { get; set; }
        public virtual profesor_horario profesor_horario { get; set; }
        public virtual ICollection<resumenclase> resumenclases { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
