//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zona
    {
        public zona()
        {
            this.profesor_zona = new HashSet<profesor_zona>();
        }
    
        public int idzona { get; set; }
        public string zona1 { get; set; }
    
        public virtual ICollection<profesor_zona> profesor_zona { get; set; }
    }
}
